/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pri.adam.ymail.client.desktop.frame;

/**
 *
 * @author adam
 */
public class YMail_TipMessage extends javax.swing.JDialog {

    /**
     * Creates new form YMail_TipMessage
     */
    public YMail_TipMessage(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        YMail_PanleBody = new javax.swing.JPanel();
        YMail_PanelTitle = new javax.swing.JPanel();
        YMail_LabelCount = new javax.swing.JLabel();
        YMail_LabelMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("通知");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModal(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        YMail_PanleBody.setToolTipText("");

        YMail_PanelTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        YMail_LabelCount.setText("您的账户：cxd@ymail.com");

        javax.swing.GroupLayout YMail_PanelTitleLayout = new javax.swing.GroupLayout(YMail_PanelTitle);
        YMail_PanelTitle.setLayout(YMail_PanelTitleLayout);
        YMail_PanelTitleLayout.setHorizontalGroup(
            YMail_PanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YMail_PanelTitleLayout.createSequentialGroup()
                .addComponent(YMail_LabelCount)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        YMail_PanelTitleLayout.setVerticalGroup(
            YMail_PanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YMail_PanelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(YMail_LabelCount)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        YMail_LabelMessage.setText("您没有收到新邮件");

        javax.swing.GroupLayout YMail_PanleBodyLayout = new javax.swing.GroupLayout(YMail_PanleBody);
        YMail_PanleBody.setLayout(YMail_PanleBodyLayout);
        YMail_PanleBodyLayout.setHorizontalGroup(
            YMail_PanleBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(YMail_PanelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(YMail_PanleBodyLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(YMail_LabelMessage)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        YMail_PanleBodyLayout.setVerticalGroup(
            YMail_PanleBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YMail_PanleBodyLayout.createSequentialGroup()
                .addComponent(YMail_PanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(YMail_LabelMessage)
                .addGap(0, 50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(YMail_PanleBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(YMail_PanleBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YMail_TipMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YMail_TipMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YMail_TipMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YMail_TipMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                YMail_TipMessage dialog = new YMail_TipMessage(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel YMail_LabelCount;
    private javax.swing.JLabel YMail_LabelMessage;
    private javax.swing.JPanel YMail_PanelTitle;
    private javax.swing.JPanel YMail_PanleBody;
    // End of variables declaration//GEN-END:variables
}
