/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pri.adam.ymail.client.desktop.frame;

/**
 *
 * @author adam
 */
public class YMail_WriteMail extends javax.swing.JDialog {

    /**
     * Creates new form YMail_WriteMail
     */
    public YMail_WriteMail(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        YMail_PanelTop = new javax.swing.JPanel();
        YMail_BtnSend = new javax.swing.JButton();
        YMail_BtnTouch = new javax.swing.JButton();
        YMail_PanelProperty = new javax.swing.JPanel();
        YMail_LabelSender = new javax.swing.JLabel();
        YMail_BtnSendMail = new javax.swing.JLabel();
        YMail_LabelReceiver = new javax.swing.JLabel();
        YMail_TextFieldReceiver = new javax.swing.JTextField();
        YMail_LabelCopyTo = new javax.swing.JLabel();
        YMail_TextFieldCopyTo = new javax.swing.JTextField();
        YMail_LabelSubject = new javax.swing.JLabel();
        YMail_TextFieldSubject = new javax.swing.JTextField();
        YMail_LabelTouch = new javax.swing.JLabel();
        YMail_BtnTouch_1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        YMail_TextAreaContent = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("写信");

        YMail_PanelTop.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        YMail_BtnSend.setText("发送");
        YMail_BtnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YMail_BtnSendActionPerformed(evt);
            }
        });

        YMail_BtnTouch.setText("附件");
        YMail_BtnTouch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YMail_BtnTouchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout YMail_PanelTopLayout = new javax.swing.GroupLayout(YMail_PanelTop);
        YMail_PanelTop.setLayout(YMail_PanelTopLayout);
        YMail_PanelTopLayout.setHorizontalGroup(
            YMail_PanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YMail_PanelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(YMail_BtnSend)
                .addGap(18, 18, 18)
                .addComponent(YMail_BtnTouch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        YMail_PanelTopLayout.setVerticalGroup(
            YMail_PanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YMail_PanelTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(YMail_PanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YMail_BtnSend)
                    .addComponent(YMail_BtnTouch))
                .addContainerGap())
        );

        YMail_PanelProperty.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        YMail_LabelSender.setText("发件人：");

        YMail_BtnSendMail.setText("cxd@ymail.com");

        YMail_LabelReceiver.setText("收件人：");

        YMail_TextFieldReceiver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YMail_TextFieldReceiverActionPerformed(evt);
            }
        });

        YMail_LabelCopyTo.setText("抄  送：");

        YMail_LabelSubject.setText("主  题：");

        YMail_LabelTouch.setText("附  件：");

        YMail_BtnTouch_1.setText("附件1/删除");
        YMail_BtnTouch_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YMail_BtnTouch_1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout YMail_PanelPropertyLayout = new javax.swing.GroupLayout(YMail_PanelProperty);
        YMail_PanelProperty.setLayout(YMail_PanelPropertyLayout);
        YMail_PanelPropertyLayout.setHorizontalGroup(
            YMail_PanelPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YMail_PanelPropertyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(YMail_PanelPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(YMail_PanelPropertyLayout.createSequentialGroup()
                        .addComponent(YMail_LabelReceiver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(YMail_TextFieldReceiver))
                    .addGroup(YMail_PanelPropertyLayout.createSequentialGroup()
                        .addGroup(YMail_PanelPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(YMail_LabelCopyTo)
                            .addComponent(YMail_LabelSubject))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(YMail_PanelPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(YMail_TextFieldSubject)
                            .addComponent(YMail_TextFieldCopyTo)))
                    .addGroup(YMail_PanelPropertyLayout.createSequentialGroup()
                        .addGroup(YMail_PanelPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(YMail_PanelPropertyLayout.createSequentialGroup()
                                .addComponent(YMail_LabelSender)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(YMail_BtnSendMail))
                            .addGroup(YMail_PanelPropertyLayout.createSequentialGroup()
                                .addComponent(YMail_LabelTouch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(YMail_BtnTouch_1)))
                        .addGap(0, 579, Short.MAX_VALUE)))
                .addContainerGap())
        );
        YMail_PanelPropertyLayout.setVerticalGroup(
            YMail_PanelPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YMail_PanelPropertyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(YMail_PanelPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YMail_LabelSender)
                    .addComponent(YMail_BtnSendMail))
                .addGap(18, 18, 18)
                .addGroup(YMail_PanelPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YMail_LabelReceiver)
                    .addComponent(YMail_TextFieldReceiver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(YMail_PanelPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YMail_LabelCopyTo)
                    .addComponent(YMail_TextFieldCopyTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(YMail_PanelPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YMail_LabelSubject)
                    .addComponent(YMail_TextFieldSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(YMail_PanelPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YMail_LabelTouch)
                    .addComponent(YMail_BtnTouch_1))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        YMail_TextAreaContent.setColumns(20);
        YMail_TextAreaContent.setRows(5);
        jScrollPane2.setViewportView(YMail_TextAreaContent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(YMail_PanelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(YMail_PanelProperty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(YMail_PanelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(YMail_PanelProperty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void YMail_TextFieldReceiverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YMail_TextFieldReceiverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YMail_TextFieldReceiverActionPerformed

    private void YMail_BtnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YMail_BtnSendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YMail_BtnSendActionPerformed

    private void YMail_BtnTouchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YMail_BtnTouchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YMail_BtnTouchActionPerformed

    private void YMail_BtnTouch_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YMail_BtnTouch_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YMail_BtnTouch_1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YMail_WriteMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YMail_WriteMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YMail_WriteMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YMail_WriteMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                YMail_WriteMail dialog = new YMail_WriteMail(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton YMail_BtnSend;
    private javax.swing.JLabel YMail_BtnSendMail;
    private javax.swing.JButton YMail_BtnTouch;
    private javax.swing.JButton YMail_BtnTouch_1;
    private javax.swing.JLabel YMail_LabelCopyTo;
    private javax.swing.JLabel YMail_LabelReceiver;
    private javax.swing.JLabel YMail_LabelSender;
    private javax.swing.JLabel YMail_LabelSubject;
    private javax.swing.JLabel YMail_LabelTouch;
    private javax.swing.JPanel YMail_PanelProperty;
    private javax.swing.JPanel YMail_PanelTop;
    private javax.swing.JTextArea YMail_TextAreaContent;
    private javax.swing.JTextField YMail_TextFieldCopyTo;
    private javax.swing.JTextField YMail_TextFieldReceiver;
    private javax.swing.JTextField YMail_TextFieldSubject;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
